# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

source 'https://github.com/CocoaPods/Specs.git'

target 'ViralSwitchDemo' do

end

target 'ViralSwitchDemoTests' do
  pod 'Specta'
  pod 'Expecta'
  pod 'Expecta+Snapshots'
end

